### ISSUE TITLE
Clean up to index builder api 

### ISSUE THREAD

**Issue by tjake** [jbellis/jvector#122]
The `GraphIndexBuilder` api can be used in two ways: for live indexing or bulk indexing.  

We should enforce checks in the api such that users don't call it incorrectly or just keep the existing builder as internal and publish two public builder apis for `IncrementalBuilder` and `BulkBuilder`.

An example of wrong usage is calling `addGraphNode` directly, followed by `build`

**Comment by jbellis** [comment]
Calling build() multiple times is also bad.  Should we just have build() check to make sure the graph is empty and throw if not?
