### ISSUE TITLE
RandomAccessVectorValues.vectorValue() signature suggestion

### ISSUE THREAD

**Issue by mdogan** [jbellis/jvector#159]
Currently `RandomAccessVectorValues.vectorValue()` API is allowed to return and re-use the same value for subsequent calls if `isValueShared()` returns true. And implementations must return a copy of the `RandomAccessVectorValues` in this case.

T think it'd be easier to interact with the `RandomAccessVectorValues` API if `vectorValue()` signature was:

```java
/**
* Return the vector value indexed at the given ordinal. 
* If the given T value is null, a new instance of type T is returned.
* Otherwise, vector's value is copied to given value reference 
* and it's returned back.
* 
* <p>For performance, callers are advised to pass a non-null T value.
* That is, you will get back the same float[]
* reference (for instance) for every requested ordinal. If you want to use those values across
* calls, you should make a copy.
*/
T vectorValue(int node, T value);
```

This way, it will be caller's responsibility to reuse the vector value, instead of implementation's. And I think `RandomAccessVectorValues` will be simpler implement. Callers may use a pool of vector values, instead of pooling `RandomAccessVectorValues`.

**Comment by jbellis** [comment]
That's an improvement for the shared-value RAVV, but not for the non-shared-value RAVV.  For instance, here are two of of the implementations of RAVV in our Cassandra code:

    public float[] vectorValue(int i)
    {
        return type.getSerializer().deserializeFloatArray(values.get(i));
    }

    public float[] vectorValue(int i)
    {
        return values.get(i);
    }
