### ISSUE TITLE
Question about OnDiskGraphIndex

### ISSUE THREAD

**Issue by siddhsql** [jbellis/jvector#164]
Hi, I have a question about the [OnDiskGraphIndex](https://github.com/jbellis/jvector/blob/main/jvector-base/src/main/java/io/github/jbellis/jvector/disk/OnDiskGraphIndex.java). I thought this index could be used to construct graphs that cannot fit in the memory but looking at the code it looks like that is not the case. The steps to use this index are:

1. first, you have to create `OnHeapIndex` which requires graph to fit in memory
2. then you write the graph to disk using `OnDiskGraphIndex.write(onHeapGraph, floatVectors, outputStream);`
3. then you can "load" this graph using the `OnDiskGraphIndex` ctor

so in essence the objective of building an index that does not fit in the memory is not satisfied. is that correct? if not, could you explain me how I can build an index which cannot fit in memory?

**Comment by jbellis** [comment]
JVector does not support building indexes larger than memory.  This is a Hard Problem in ANN indexing; the DiskANN paper describes a way to do it by partitioning the nodes (assigning each node to multiple partitions), then indexing the partitions and combining these sub-indexes.  However, there's a significant performance penalty from the partitioning step (the example they give is Deep1B which takes 2.5x times longer to build with this approach vs in-memory), and I'm not interested in adding code to do this.

**Comment by jbellis** [comment]
I wrote up what I think would be the "right" way to add larger than memory construction: https://github.com/jbellis/jvector/issues/168

**Comment by siddhsql** [comment]
I wanted to revisit this. I was reading the project documentation today and the [README](https://github.com/jbellis/jvector/?tab=readme-ov-file#step-6-building-a-larger-than-memory-index) says:

>JVector can also apply two-phase search to allow building a larger than memory index–only the compressed vectors are kept in memory, while the full-sized ones are kept in the on-disk index...

then it goes onto saying:

>Finally, we need to run cleanup() and write the index and the PQVectors to disk:

the problem is that in a real-world system, data will be coming in _continuously_ so you can never be "done with it". IIUC `cleanup` assumes you will have no more data coming in. any comment on this? also does this code work with v2 or is it using v3 API?

**Comment by jbellis** [comment]
Right, there's a strong Cassandra flavor here -- Cassandra uses log structured storage, so there is in fact a "done with it" stage for a given Memtable / SSTable.

OnHeapGraphIndex.save / GraphIndexBuilder.load are designed for the use case you have in mind where you want to checkpoint an index but keep it "live."  I believe this is what @mdogan and Upstash use.

**Comment by mdogan** [comment]
Yes, that's how we do. We are persisting and restoring builder state for incremental indexing.

**Comment by siddhsql** [comment]
Ok, thanks for the update.
