### ISSUE TITLE
incremental indexing

### ISSUE THREAD

**Issue by siddhsql** [jbellis/jvector#165]
Hello, is there any code sample showing how to build the index incrementally when all the vectors are not available upfront?

currently, i don't see any way to do this. the `GraphIndexBuilder` requires list of vectors:

```
public GraphIndexBuilder(
            RandomAccessVectorValues<T> vectorValues,
            VectorEncoding vectorEncoding,
            VectorSimilarityFunction similarityFunction,
            int M,
            int beamWidth,
            float neighborOverflow,
            float alpha) {
```

and `addGraphNode` also requires the list of vectors:

```
public long addGraphNode(int node, RandomAccessVectorValues<T> vectors) {
```

I am looking for an API where `GraphIndexBuilder` will not require `vectorValues` and `addGraphNode` should look like:

```
public long addGraphNode(int node, float[] vector) {
```

**Comment by jbellis** [comment]
GIB requires a reference to the RAVV that you're going to add vectors to, but it doesn't need to contain all the vectors (or any vectors) when it's created.

addGraphNode requires the reference a second time because I was sloppy: https://github.com/jbellis/jvector/issues/158
