### ISSUE TITLE
size() does not factor in deleted nodes

### ISSUE THREAD

**Issue by siddhsql** [jbellis/jvector#167]
this fails for me:

```
        int sizeBefore = builder.graph.size();
        builder.markNodeDeleted(n);
        int sizeAfter = builder.graph.size();
        assertEquals(sizeAfter, sizeBefore - 1);
```

refer [this](https://github.com/jbellis/jvector/blob/main/jvector-tests/src/test/java/io/github/jbellis/jvector/graph/TestDeletions.java#L53)

**Comment by jbellis** [comment]
That's because the actual number of nodes doesn't change until you run cleanup.
