### ISSUE TITLE
Shouldn't GraphIndexBuilder.markNodeDeleted be thread-safe?

### ISSUE THREAD

**Issue by mdogan** [jbellis/jvector#174]
As far as I understand, `GraphIndexBuilder.markNodeDeleted` uses `GrowableBitSet.set()` in `OnHeapGraphIndex`. `GrowableBitSet` uses `java.util.BitSet` as the backend, which is not thread-safe.

**Comment by jbellis** [comment]
You're right.  We have an AtomicFixedBitSet but not an Atomic Growable.

I'd be fine with either adding an AtomicGrowableBitSet or just wrapping the uses here in `synchronized`.

**Comment by jbellis** [comment]
... or maybe adding a SynchronizedGrowableBitSet that does the synchronization internally is the easiest option.  Depends on how much concurrency you need for deletes.
