### ISSUE TITLE
Possible race between GraphIndexBuilder.cleanup() and GraphSearcher

### ISSUE THREAD

**Issue by mdogan** [jbellis/jvector#188]
Is running `GraphIndexBuilder::cleanup` concurrently with `GraphSearcher::search` allowed when `GraphSearcher` is built with `GraphIndexBuilder::getGraph`? 

So usecase here is, some nodes are marked as deleted and then `GraphIndexBuilder::cleanup` is run to actually remove them, while a few `GraphSearcher`s are used to query the index.  See following code as an example;

```java
public static void main(String[] args) throws Exception {
    var baseVectors = SiftLoader.readFvecs("siftsmall/siftsmall_base.fvecs");
    var ravv = new ListRandomAccessVectorValues(baseVectors, 128);
    var builder = new GraphIndexBuilder<>(ravv, VectorEncoding.FLOAT32, VectorSimilarityFunction.COSINE, 32, 100, 1.5f, 1.5f);
    builder.build();

    // Delete nodes one by one
    Thread thread = new Thread(() -> {
        for (int i = 0; i < baseVectors.size(); i++) {
            builder.markNodeDeleted(i);
            builder.cleanup();
            LockSupport.parkNanos(TimeUnit.MILLISECONDS.toNanos(10));
        }
    });
    thread.setDaemon(true);
    thread.start();

    // Run search in a loop
    var searcher = new Builder<>(builder.getGraph().getView()).withConcurrentUpdates().build();
    while (true) {
        for (float[] queryVector : baseVectors) {
            var scoreFunction = new ExactScoreFunction() {
                @Override
                public float similarityTo(int nodeId) {
                    return VectorSimilarityFunction.COSINE.compare(queryVector, ravv.vectorValue(nodeId));
                }
            };
            searcher.search(scoreFunction, null, 100, Bits.ALL);
        }
    }
}
```

This code fails with `java.lang.NullPointerException: Cannot invoke "io.github.jbellis.jvector.graph.ConcurrentNeighborSet.iterator()" because "neighbors" is null`:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.github.jbellis.jvector.graph.ConcurrentNeighborSet.iterator()" because "neighbors" is null
	at io.github.jbellis.jvector.graph.OnHeapGraphIndex$ConcurrentGraphIndexView.getNeighborsIterator(OnHeapGraphIndex.java:272)
	at io.github.jbellis.jvector.graph.GraphSearcher.resume(GraphSearcher.java:321)
	at io.github.jbellis.jvector.graph.GraphSearcher.searchInternal(GraphSearcher.java:241)
	at io.github.jbellis.jvector.graph.GraphSearcher.search(GraphSearcher.java:144)
	at io.github.jbellis.jvector.graph.GraphSearcher.search(GraphSearcher.java:168)
	at io.github.jbellis.jvector.graph.GraphSearcher.search(GraphSearcher.java:189)
	at io.github.jbellis.jvector.example.Test.main(Test.java:44)

**Comment by mdogan** [comment]
Following patch _naively_ fixes this issue, but not sure if it's the correct way. I think otherwise, we will need to fix this in GraphSearcher::resume` method.

```
---
Index: jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java b/jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java
--- a/jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java	(revision 063b216662e11d57d0428f487a9a2f1da8a234d8)
+++ b/jvector-base/src/main/java/io/github/jbellis/jvector/graph/OnHeapGraphIndex.java	(date 1705864121363)
@@ -255,7 +255,21 @@
         }
 
         public NodesIterator getNeighborsIterator(int node) {
-            return getNeighbors(node).iterator();
+            ConcurrentNeighborSet neighbors = getNeighbors(node);
+            if (neighbors == null) {
+                return new NodesIterator(0) {
+                    @Override
+                    public boolean hasNext() {
+                        return false;
+                    }
+
+                    @Override
+                    public int nextInt() {
+                        throw new UnsupportedOperationException();
+                    }
+                };
+            }
+            return neighbors.iterator();
         }
 
         @Override
```

**Comment by jbellis** [comment]
It's not designed to support concurrent cleanup + search, because cleanup renumbers nodes as it fills in the "holes" left by deleted ones.  So your patch will prevent it from NPE but it will still produce incorrect results if it reads from a list of neighbors that has not yet been updated with the new ordinals.

Ideally we could use a transactional data structure and just save a reference to the current version in the View, and we're sort of halfway there already using AtomicReference in CNS, but I don't see how we can replace DenseIntMap with anything close to as high-performance so I think that approach is a dead end.  (Happy to be wrong!)

As a second-best approach, we could add an optional ReadWriteLock to GraphBuilder where inserts and searches take out "read" locks and cleanup takes a "write" lock.  It should be optional so that users who don't need concurrent cleanups don't have to pay the lock tax.  This would require some restructuring of GraphBuilder and GraphSearcher so that the searcher has the reference to the lock as well.  As a first try I would probably add a withConcurrentCleanup(builder) method to GS.

**Comment by mdogan** [comment]
Thanks for the explanation @jbellis. I think we can sync externally while using cleanup, indexing and search. No need to add this complexity to the core library.

But it would be better to document this in `cleanup`'s doc. Currently it only says:

```
May be called multiple times, but should not be called during concurrent modifications to the graph.
```
