### ISSUE TITLE
Is GraphIndexBuilder leaking ThreadLocals ?

### ISSUE THREAD

**Issue by mdogan** [jbellis/jvector#189]
`GraphIndexBuilder` creates a few thread-local based `PoolingSupport` instances. And these thread-locals remain live as long as the FJP threads (common or custom) used in `GraphIndexBuilder` are alive. When many `GraphIndexBuilder` come and go during the lifecycle of the application, heap usage always grows. Following artificial code shows that:

```java
public static void main(String[] args) throws Exception {
    var baseVectors = SiftLoader.readFvecs("siftsmall/siftsmall_base.fvecs");
    var ravv = new ListRandomAccessVectorValues(baseVectors, 128);
    printMemory();

    for (int i = 0; i < 100; i++) {
        build(ravv);
        printMemory();
    }
}

private static void build(ListRandomAccessVectorValues ravv) {
    var builder = new GraphIndexBuilder<>(ravv, VectorEncoding.FLOAT32, ...);
    builder.build();
}

private static void printMemory() {
    System.gc();
    Runtime r = Runtime.getRuntime();
    System.out.println((r.totalMemory() - r.freeMemory()) / 1024 / 1024 + " MB");
}
```

Not sure how can we reset & reuse an existing `GraphIndexBuilder`.

**Comment by jbellis** [comment]
My first reaction is that it's probably easiest to implement AutoCloseable, but I would also support a reset() method if that makes more sense.

**Comment by mdogan** [comment]
Not sure how `AutoCloseable` will fix this, because thread-locals should be removed by the specific threads created them. 

`reset()` makes sense I think and sounds a better solution.

**Comment by mdogan** [comment]
Also the same issue is in `ProductQuantization.compute` and `BinaryQuantization.compute` too. They can create thread-locals too.

**Comment by mdogan** [comment]
Fixed by https://github.com/jbellis/jvector/pull/206
