### ISSUE TITLE
Quantization does not reduce memory usage

### ISSUE THREAD

**Issue by siddhsql** [jbellis/jvector#192]
In my experiments I find that quantization does not reduce memory usage. E.g., I tried running JVector on the massive Sift1B dataset. d=128. I was only able to index about 10M vectors on a 128GB RAM machine with or without quantization before OOM (M=d=128). does anyone have same experience?

**Comment by jbellis** [comment]
See https://github.com/jbellis/jvector/issues/168

**Comment by siddhsql** [comment]
this is a separate issue btw. the purpose of quantization is to compress
vectors and thus reduce memory consumption but I do not see that. With PQ
on and M=d, a 4 byte float is stored as 1 byte so in theory there is a 4x
compression storing the quantized representation. but in my tests I find
that the RAM usage is more or less the same whether I am using quantization
or not. My suspicion is that Java is not garbage collecting transient
vectors that are generated by the decode method of the PQ (when doing
distance calculation we have to decode the byte into a float) but I have
not been able to confirm this and do not have another theory. i am curious
if anyone else has also reproduced this issue.
