### ISSUE TITLE
DenseIntMap size can become permanently out-of-sync

### ISSUE THREAD

**Issue by jkni** [jbellis/jvector#218]
DenseIntMap uses an optimistic read on puts, with a write lock on removal and resizing the backing array. DenseIntMap retries reads if its optimistic read stamp was invalidated. If put/remove run for the same key concurrently and there is no preexisting value for that key, it can be that the put modifies the backing array, the remove takes a write lock and removes the value (decrementing size), and the put retries (due to invalidated stamp), putting the value in the map once again. This will result in one decrement (from the remove) and one increment (from the put retry), inserting a new value in the map with no change in the size. This divergence will result in a permanent underaccounting for size.

**Comment by jbellis** [comment]
I think you can get an inconsistency even with two puts?

Thread 1: begin do/while loop
Thread 2: start increasing capacity
T1: add k,v to objects
T2: copy objects [including k, v] to newArray, promote newArray to active objects
T1: stamp is invalid, retry
T1: objects.getAndSet returns non-null, isInsert is false, so we do not increment size

I think we may have to switch to a pessimistic ReadWriteLock which makes me sad.

**Comment by jbellis** [comment]
Possibly we could replace O(1) size() with a combination of

- O(1) isEmpty
- O(1) modificationCount
- O(N) size() (just count the non-null keys)

**Comment by jbellis** [comment]
It doesn't look like the difference in optimistic vs pessimistic on put is material, which makes sense b/c build does much more expensive things when adding a new node.  So my PR takes that approach to keep things simple.
