### ISSUE TITLE
Consider removing caching of vectors in CachingGraphIndex

### ISSUE THREAD

**Issue by jkni** [jbellis/jvector#222]
The CachingGraphIndex caches neighbor iterators and vectors for a certain radius around the graph's entry point. This made sense with our previous design, which kept track of visited vectors for potential results during the search. Now that we lazily look up vectors, it might not be a good use of resources to keep the vector in memory for all cached nodes.

**Comment by jbellis** [comment]
would be interesting to see how many of the cached nodes end up in the resultset

**Comment by jbellis** [comment]
or just rip it out of the cachedview implementation and see if it gets slower

**Comment by jbellis** [comment]
My results.  TLDR the difference is not significant wrt the normal run variance.

[cache enabled run 1]
ada002-100k: 99920 base and 9760 query vectors created, dimensions 1536
Build (full res) M=32 ef=100 in 246.60s with avg degree 31.99 and 0.63 short edges
Uncompressed vectors
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.9515 in 2.55s after 27,273,400 nodes visited
 Query top 100/2 recall 0.9803 in 4.35s after 46,989,610 nodes visited
Using OnHeapGraphIndex(size=99920, entryPoint=91187):
 Query top 100/1 recall 0.9515 in 2.36s after 27,273,400 nodes visited
 Query top 100/2 recall 0.9803 in 4.33s after 46,989,610 nodes visited
ProductQuantization(M=192) loaded from PQ_ada002-100k_192_256_false_-1.0
ProductQuantization(M=192) encoded 99920 vectors [22.85 MB] in 1.44s
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.7179 in 1.75s after 28,421,086 nodes visited
 Query top 100/2 recall 0.9111 in 2.25s after 48,869,606 nodes visited
Using CachingGraphIndex(graph=OnDiskLVQGraphIndex(size=99920, entryNode=91187)):
 Query top 100/1 recall 0.7179 in 1.62s after 28,421,086 nodes visited
 Query top 100/2 recall 0.9109 in 2.06s after 48,869,606 nodes visited

[cache enabled run 2]
ada002-100k: 99920 base and 9760 query vectors created, dimensions 1536
Build (full res) M=32 ef=100 in 15.30s with avg degree 31.99 and 0.63 short edges
Uncompressed vectors
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.9518 in 2.56s after 27,218,948 nodes visited
 Query top 100/2 recall 0.9804 in 4.20s after 46,968,910 nodes visited
Using OnHeapGraphIndex(size=99920, entryPoint=91187):
 Query top 100/1 recall 0.9518 in 2.36s after 27,218,948 nodes visited
 Query top 100/2 recall 0.9804 in 4.27s after 46,968,910 nodes visited
ProductQuantization(M=192) loaded from PQ_ada002-100k_192_256_false_-1.0
ProductQuantization(M=192) encoded 99920 vectors [22.85 MB] in 1.40s
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.7197 in 1.54s after 28,445,614 nodes visited
 Query top 100/2 recall 0.9113 in 2.14s after 48,839,380 nodes visited
Using CachingGraphIndex(graph=OnDiskLVQGraphIndex(size=99920, entryNode=91187)):
 Query top 100/1 recall 0.7197 in 1.66s after 28,445,614 nodes visited
 Query top 100/2 recall 0.9110 in 2.08s after 48,839,380 nodes visited

[cache disabled run 1]
ada002-100k: 99920 base and 9760 query vectors created, dimensions 1536
Build (full res) M=32 ef=100 in 15.13s with avg degree 31.99 and 0.63 short edges
Uncompressed vectors
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.9521 in 2.47s after 27,248,092 nodes visited
 Query top 100/2 recall 0.9802 in 4.23s after 46,979,604 nodes visited
Using OnHeapGraphIndex(size=99920, entryPoint=91187):
 Query top 100/1 recall 0.9521 in 2.37s after 27,248,092 nodes visited
 Query top 100/2 recall 0.9802 in 4.29s after 46,979,604 nodes visited
ProductQuantization(M=192) loaded from PQ_ada002-100k_192_256_false_-1.0
ProductQuantization(M=192) encoded 99920 vectors [22.85 MB] in 1.29s
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.7191 in 1.65s after 28,298,190 nodes visited
 Query top 100/2 recall 0.9112 in 2.13s after 48,756,110 nodes visited
Using CachingGraphIndex(graph=OnDiskLVQGraphIndex(size=99920, entryNode=91187)):
 Query top 100/1 recall 0.7191 in 1.39s after 28,298,190 nodes visited
 Query top 100/2 recall 0.9110 in 2.07s after 48,756,110 nodes visited

[cache disabled run 2]
ada002-100k: 99920 base and 9760 query vectors created, dimensions 1536
Build (full res) M=32 ef=100 in 15.12s with avg degree 31.99 and 0.63 short edges
Uncompressed vectors
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.9522 in 2.50s after 27,300,932 nodes visited
 Query top 100/2 recall 0.9805 in 4.23s after 47,052,476 nodes visited
Using OnHeapGraphIndex(size=99920, entryPoint=91187):
 Query top 100/1 recall 0.9522 in 2.36s after 27,300,932 nodes visited
 Query top 100/2 recall 0.9805 in 4.31s after 47,052,476 nodes visited
ProductQuantization(M=192) loaded from PQ_ada002-100k_192_256_false_-1.0
ProductQuantization(M=192) encoded 99920 vectors [22.85 MB] in 1.30s
Using CachingGraphIndex(graph=OnDiskGraphIndex(size=99920, entryPoint=91187)):
 Query top 100/1 recall 0.7193 in 1.60s after 28,489,222 nodes visited
 Query top 100/2 recall 0.9113 in 2.21s after 48,914,184 nodes visited
Using CachingGraphIndex(graph=OnDiskLVQGraphIndex(size=99920, entryNode=91187)):
 Query top 100/1 recall 0.7193 in 1.46s after 28,489,222 nodes visited
 Query top 100/2 recall 0.9111 in 2.09s after 48,914,184 nodes visited
