### ISSUE TITLE
How can we get a unique id after vector recall

### ISSUE THREAD

**Issue by leohou0430** [jbellis/jvector#253]
As far as I know, currently the only thing returned in SearchResult.NodeScore is node, a value that represents the index of the RandomAccessVectorValues.

How can we get a unique id after vector recall, such as the docid returned in ES, where docid can be customized at index time.

**Comment by mdogan** [comment]
You can store a mapping between `nodeId <-> docid` in an external system (database, filesystem, in-memory hashtable etc).

**Comment by leohou0430** [comment]
> You can store a mapping between `nodeId <-> docid` in an external system (database, filesystem, in-memory hashtable etc).

There isn't a separate place to store it in the index, so this seems to be the only way for now. I understand that the order of this index is supposed to be determined after the entire index is complete, how exactly should this be handled? I looked through the test cases and didn't see the corresponding code

**Comment by mdogan** [comment]
`nodeId` is the ordinal of the vector value provided by `RandomAccessVectorValues`. It's already known upfront. You already provide an instance if `RandomAccessVectorValues` to JVector. You should just keep a mapping unique id for every ordinal.

But note that, if you delete some values then ordinals can change and you need to update the mapping too.

**Comment by leohou0430** [comment]
> `nodeId` is the ordinal of the vector value provided by `RandomAccessVectorValues`. It's already known upfront. You already provide an instance if `RandomAccessVectorValues` to JVector. You should just keep a mapping unique id for every ordinal.
> 
> But note that, if you delete some values then ordinals can change and you need to update the mapping too.


In the way you said, I wrote a test case with the following code, please help me to see if it is correct or not

```
@Test
    public void testNodeDocIdMapping() {

        var sourceData = List.of(new TestVectorItem(new float[]{-1, -1}, 11L),
            new TestVectorItem(new float[]{1.5f, 1.4f}, 13L),
            new TestVectorItem(new float[]{0.9f, 0.9f}, 14L),
            new TestVectorItem(new float[]{1, 1}, 12L));

        Map<Integer, Long> nodeMap = new HashMap<>();
        List<VectorFloat<?>> rawVectors = new ArrayList<>();
        for (int i = 0; i < sourceData.size(); i++) {
            rawVectors.add(vectorTypeSupport.createFloatVector(sourceData.get(i).getVectors()));
            nodeMap.put(i, sourceData.get(i).getDocId());
        }

        var vectors = new ListRandomAccessVectorValues(rawVectors, 2);
        var builder = new GraphIndexBuilder(vectors, VectorSimilarityFunction.EUCLIDEAN, 2, 2, 1.0f, 1.0f);

        try (var graph = builder.build()) {
            var qv = vectorTypeSupport.createFloatVector(new float[]{0.5f, 0.5f});
            var results = GraphSearcher.search(qv, 4, vectors, VectorSimilarityFunction.EUCLIDEAN, graph, Bits.ALL);
            SearchResult.NodeScore[] nodes = results.getNodes();
            for (SearchResult.NodeScore nodeScore : nodes) {
                int node = nodeScore.node;
                float[] ff = (float[]) rawVectors.get(node).get();
                float score = nodeScore.score;
                System.out.println("float[0]=" + ff[0] + ", float[1]=" + ff[1] + ", node=" + node + ", score=" + score + ", docId=" + nodeMap.get(node));
            }
        }
    }

    public static class TestVectorItem {
        public float[] vectors;
        public long docId;

        public TestVectorItem(float[] vectors, long docId) {
            this.vectors = vectors;
            this.docId = docId;
        }

        public float[] getVectors() {
            return vectors;
        }
        public long getDocId() {
            return docId;
        }
    }
```

**Comment by jbellis** [comment]
That looks reasonable to me.

**Comment by leohou0430** [comment]
> That looks reasonable to me.

tks
