### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#279]
JDK 20 did not compile using `mvn compile`, installed JDK 22 does not compile either.  Reverted to JDK 20 now get:

`12:23:22,797 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project jvector-native: Fatal error compiling: error: release version 22 not supported -> [Help 1]`

JDK 22 was uninstalled.  

`java -version`
`java version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)`

`echo $JAVA_HOME`
`/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home`

Why is maven used rather than gradle?

Branch `main` has a compilation error in Idea, screenshot:
<img width="826" alt="Screenshot 2024-04-14 at 12 30 50 PM" src="https://github.com/jbellis/jvector/assets/166993754/d84d4799-a5f1-4004-91ba-4998695ccefe">

Lucene has updated vector search and is faster, the benchmarks are out of date.

Lucene benchmark does not list Lucene version used.

Including the Lucene benchmark in the jvector repo would be useful.

Release notes with the detailed changes would be helpful.  An example in Lucene is `CHANGES.txt`

Why not use JMH?

2 spaces instead of 4 would make the code easier to read.

**Comment by jbellis** [comment]
JDK 22 is required to build from source (but not to run it).

Changes are listed in UPGRADING.md.

We're happy with our conventions, thanks.

**Comment by rickjamesthe6th** [comment]
Perhaps it was confusing to place separate issues into one issue.

**Comment by rickjamesthe6th** [comment]
Closing this issue for, opening separate issues.
