### ISSUE TITLE
Add Lucene benchmark code used

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#282]
The README shows a benchmark vs. Lucene however there is no way to verify as the benchmark code is missing.

**Comment by jbellis** [comment]
That code lives at https://github.com/jbellis/hnswrecall and does not belong in JVector

**Comment by rickjamesthe6th** [comment]
It'd be helpful for future devs to add https://github.com/jbellis/hnswrecall to the README.  Also an explanation for branching Lucene.

**Comment by jbellis** [comment]
teaching people how to benchmark lucene is not one of my goals.

**Comment by rickjamesthe6th** [comment]
I opened an issue on hnswrecall for an explanation of the Lucene branch.  Branching Lucene should not be necessary and negates the benchmark results since no one actually uses the branch.

**Comment by rickjamesthe6th** [comment]
hnswrecall only benchmarks Lucene?  2 separate benchmarks with different parameters?  I need an apples to apples comparison, I'm only interested in query times atm.
