### ISSUE TITLE
mvn compile yields error message release version 22 not supported

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#283]
JDK22 installed.  Using `mvn compile` on the `main` branch, commit `70a6df8825319c6c031cf5cfd48f58f19d9c0c85` yields:

<img width="1064" alt="Screenshot 2024-04-15 at 11 03 05 AM" src="https://github.com/jbellis/jvector/assets/166993754/f0c7b5b4-427f-4143-8f22-8533dbbf4f45">

**Comment by jbellis** [comment]
As noted in your other issue, jdk 22 is required to build jvector `main`.

**Comment by rickjamesthe6th** [comment]
To reiterate "JDK22 installed. " in the issue description.

**Comment by jbellis** [comment]
the build is not using jdk 22.  set JAVA_HOME.
