### ISSUE TITLE
package jdk.incubator.vector is not visible

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#287]
Running the unit tests in Intellij with Oracle JDK 22 yields:

`/jvector/jvector-native/src/main/java/io/github/jbellis/jvector/vector/VectorSimdOps.java:21:21
java: package jdk.incubator.vector is not visible
  (package jdk.incubator.vector is declared in module jdk.incubator.vector, which is not in the module graph)`

I didn't see anything in the README if additional options need to be set.

Also I thought the unit tests were running earlier today.

**Comment by rickjamesthe6th** [comment]
Downloaded jvector into a new directory, that one causes Intellij to hang at open.

**Comment by jbellis** [comment]
"./mvnw compile test" is all you need

**Comment by jbellis** [comment]
getting it to run in your ide of choice is your responsibility
