### ISSUE TITLE
The most advanced vector search algo

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#288]
"Experiment results demonstrate that SPANN is 2× faster than the state-of-the-art ANNS solution DiskANN to reach the same recall quality 90% with same memory cost in three billion-scale datasets."

SPANN solves the memory issue.

https://www.microsoft.com/en-us/research/publication/spann-highly-efficient-billion-scale-approximate-nearest-neighbor-search/

Also solved is the filtering problem.

https://www.usenix.org/system/files/osdi23-zhang-qianxi_1.pdf

**Comment by jbellis** [comment]
Yes, if I were building an index for static datasets, I would probably base it on SPANN.

**Comment by rickjamesthe6th** [comment]
I believe they've solved that as well.  

https://dl.acm.org/doi/10.1145/3600006.3613166

**Comment by jbellis** [comment]
Thanks for the pointer, I haven't seen SPFresh before.  Will check it out for JVector 4.

**Comment by anbu1506** [comment]
@jbellis is there any update on supporting SPFresh in jvector?
