### ISSUE TITLE
Is jvector going to implement FreshDiskANN

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#289]
Are there plans to incorporate FreshDiskANN for more efficient merging (in other words, avoid the monolithic and memory intensive full rebuild the world on compaction that does not scale as the vector index grows) into jvector? 

"The Cost of StreamingMerge. The StreamingMerge procedure with 40 threads takes around 16000 seconds to merge 30M inserts and deletes into a 800M point LTI (a 7.5% change), which is 8.5% of the ≈ 190000 seconds it would take to rebuild the index from scratch with a similar thread-count."

https://arxiv.org/pdf/2105.09613.pdf

**Comment by jbellis** [comment]
No. We're doing this instead

> Support for larger-than-memory graph construction by using quantized vectors + rerank for the searches performed during construction.

In other words -- FreshDiskANN is a clever hack to work around not being able to update large graphs, we're fixing the root problem instead.

**Comment by rickjamesthe6th** [comment]
Sounds like this issue: https://github.com/jbellis/jvector/issues/168

**Comment by rickjamesthe6th** [comment]
It would help if this project used PRs or had an explanation of the various branches.

**Comment by rickjamesthe6th** [comment]
> rerank for the searches performed during construction

Why are searches being performed on a merging index?

**Comment by jbellis** [comment]
I'm not sure wym by "a merging index."

**Comment by rickjamesthe6th** [comment]
Merging index = compaction.  

Orthogonally, presumably separate jvector files/instances can be searched on and their results merged.  Is there a unit test for this case?

**Comment by jbellis** [comment]
the point is that our approach means you only need a single index, which is significantly faster than merging results from multiple indexes

**Comment by rickjamesthe6th** [comment]
So no LSM (log-structured merge-tree).  There's going to be one big jvector index for multiple sstables?  I thought jvector was integrating with something in Cassandra.

**Comment by jbellis** [comment]
No LSM in JVector.  Other projects can consume it as makes sense for them.
