### ISSUE TITLE
GraphSearcher has inconsistent new line brackets

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#294]
Class `GraphSearcher` methods `searchInternal`, `search`, `extractScores`.

Class `BuildScoreProvider` method `pqBuildScoreProvider`.

**Comment by jbellis** [comment]
I brace on newline when the header spans multiple lines.

Please don't open issues when the project style doesn't match your own.

**Comment by rickjamesthe6th** [comment]
> I brace on newline when the header spans multiple lines.

-1

**Comment by rickjamesthe6th** [comment]
Your style aint consistent.
```

public SearchResult search(SearchScoreProvider scoreProvider,
                               int topK,
                               float threshold,
                               Bits acceptOrds) {
        return search(scoreProvider, topK, threshold, 0.0f, acceptOrds);
    }
```

**Comment by rickjamesthe6th** [comment]
Also these issues are being closed hastily without a proper resolution.
