### ISSUE TITLE
FusedADC* classes could use some more explanation 

### ISSUE THREAD

**Issue by rickjamesthe6th** [jbellis/jvector#295]
Specifically what "Quick ADC-style scoring by fusing PQ-encoded" means and why it's useful.  Un-spelled out acronyms sound like gibberish unless commonly known.

**Comment by jbellis** [comment]
Docs are coming, in the meantime this is the reference https://arxiv.org/abs/1812.09162

**Comment by rickjamesthe6th** [comment]
Unfortunately the abstract at https://arxiv.org/abs/1812.09162 doesn't spell out wtf ADC means either.

**Comment by jbellis** [comment]
come on man, take a little initiative https://chat.openai.com/share/f2b86f08-8064-453f-9561-bc84aac0ec7c

**Comment by rickjamesthe6th** [comment]
Here's an example of acronyms done properly:

> Implements Locally-Adaptive Vector Quantization (LVQ)
