### ISSUE TITLE
mvn exec does not build before executing

### ISSUE THREAD

**Issue by jbellis** [jbellis/jvector#32]
so if you don't "clean install" manually first you will either get ClassNotFoundException (moderately confusing and bad) or it will silently run the last version that you built (very very bad).

**Comment by zznate** [comment]
Oooh, yeah should be able to change where in the lifecycle the invocation gets triggered. Looking..

**Comment by zznate** [comment]
Ok, so there are a couple of options. First - and I'm going to do this real quick - is update the README to use `mvn clean install exec:exec@bench`. The Maven Way™ would be to setup profiles which chains together `clean`,`install`, and `exec` into it's own workflow for that profile. This would be invoked via `mvn -P run-bench`.
