### ISSUE TITLE
Decouple vector values from index creation

### ISSUE THREAD

**Issue by benayat** [jbellis/jvector#330]
To create an index, one has to first get vector values, create a RAV, create score provider, and then create the GraphIndex, providing the rav, score provider and dimensions, and more . Is it possible to create an index without vector values, and only add vectors after index creation?

**Comment by jbellis** [comment]
Hi Benaya, the README section that begins "Once that’s done, we can index vectors one at a time" shows how to call addGraphNode without needing an RAVV.  How would you suggest making this more clear?

**Comment by jbellis** [comment]
Are you using an old version?
```
    public GraphIndexBuilder(BuildScoreProvider scoreProvider,
                             int dimension,
                             int M,
                             int beamWidth,
                             float neighborOverflow,
                             float alpha)
```

**Comment by benayat** [comment]
I apologize, I wasn't clear enough from the beginning. To call GraphIndexBuilder constructor, you must provide a BuildScoreProvider. and to create BuildScoreProvider, you must provide either PQVectors, or RandomAccessVectorValues, meaning - you can't create an empty index. Am I wrong?

**Comment by jbellis** [comment]
Both PQV and RAVV can be backed by a mutable collection (that starts empty).  The README section that I pointed to above gives an example of this.

(PQV needs a ProductQuantization but RAVV of course does not.)

**Comment by benayat** [comment]
Thanks.
