### ISSUE TITLE
ensure builds are jdk-11 compatible

### ISSUE THREAD

**Issue by jbellis** [jbellis/jvector#38]
thinking of OSS C* here

**Comment by jbellis** [comment]
when I set intellij to language level 11 it does not bitch at me even when I deliberately use newer constructs like enhanced switch

**Comment by jbellis** [comment]
this is actually a blocker, the C* ant build is even more fragile than I thought and getting it in shape for jdk 20 is more than I can tackle this week

**Comment by zznate** [comment]
Intellij may be overridden by the explicit setting in the maven compiler plugin if you imported this as a "maven project" when you set it up. I should be able to gerfingerpoken the settings in maven-compiler-plugin.

**Comment by zznate** [comment]
Ok, so there is a bunch of `condition` switches in ant checking for JDK11. I'm going to follow this pattern and toggle the JAR version to use if 20 is not detected.

**Comment by zznate** [comment]
@jbellis the jars are all getting built, so can probably merge this and i'll move over to datastax-cassandra

**Comment by jbellis** [comment]
Ship it!

**Comment by zznate** [comment]
On the ant side, this became a lot more complicated. A "classified" version of the jvector jar, eg. `jvector-1.0-SNAPSHOT-jdk11.jar` can be referenced via maven with the usually dependency incantation with the added classifier property like so: 
```
          <dependency> 
            <groupId>com.github.jbellis</groupId> 
            <artifactId>jvector</artifactId> 
            <version>1.0-SNAPSHOT</version> 
            <classifier>jdk11"</classifier>
         </dependency>
```
However, adding this to `build.xml`, it does not appear that classifier is supported correctly:
```
          <dependency groupId="com.github.jbellis" artifactId="jvector" version="1.0-SNAPSHOT" scope="provided" classifier="jdk11"/>
```
as it results in the following error:
```
BUILD FAILED
/Users/zznate/Documents/GitHub/ds-cassandra/.build/build-resolver.xml:168: The following error occurred while executing this line:
/Users/zznate/Documents/GitHub/ds-cassandra/.build/build-resolver.xml:86: Task [resolver:pom] failed after [3] attempts; giving up.
Error messages:
Could not load POM /Users/zznate/Documents/GitHub/ds-cassandra/build/dse-db-4.0.7-SNAPSHOT.pom: 1 problem was encountered while building the effective model for com.datastax.dse:dse-db-all:4.0.7-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for com.github.jbellis:jvector:jar is missing. @ line 226, column 17
```

When removed, and replaced with `version="1.0-SNAPSHOT-jdk11"` (also a legal syntax for dependencies), the ant resolver will not look at the local repository first. Normally, you can force maven into offline mode for snapshots with the single `-o` flag, but there is no analog to this in ant-resolver:

```
resolver-retrieve-build:
[resolver:resolve] Downloading https://repo1.maven.org/maven2/com/github/jbellis/jvector/1.0-SNAPSHOT-jdk11/jvector-1.0-SNAPSHOT-jdk11.pom
[resolver:resolve] Downloading https://repo.maven.apache.org/maven2/com/github/jbellis/jvector/1.0-SNAPSHOT-jdk11/jvector-1.0-SNAPSHOT-jdk11.pom
[resolver:resolve] Downloading https://repo.datastax.com/dse/com/github/jbellis/jvector/1.0-SNAPSHOT-jdk11/jvector-1.0-SNAPSHOT-jdk11.pom
```

Removing the classifier and just using the snapshot name by itself: `version="1.0-SNAPSHOT"` with no classifier and `scope="provided"` works as intended, pulling in the jar from the local repository.

**Comment by tjake** [comment]
Should be good now with #55
