### ISSUE TITLE
find out how much we can compress openai embeddings vectors

### ISSUE THREAD

**Issue by jbellis** [jbellis/jvector#62]
right now Bench hardcodes dimensions at

```
        var pqDims = ds.baseVectors.get(0).length / 2;
```

because with the datasets from ann-benchmarks (nytimes-256, glove-200) this gives virtually no recall loss at overquery=2.

however, OpenAI's embeddings vectors are ridiculously overparameterized, we should be able to get more aggressive there

length / 4 ?  length / 8?  let's find out

**Comment by jbellis** [comment]
Let's use the following grid for the existing parameters
```
        var mGrid = List.of(16, 24, 32, 48);
        var efConstructionGrid = List.of(100, 200, 400);
        var efSearchFactor = List.of(1, 2);
```

**Comment by dlg99** [comment]
Raw output and plots for:
```java
        var files = List.of(
                "../ivec/pages_ada_002",
                "../hdf5/nytimes-256-angular.hdf5",
                "../hdf5/glove-100-angular.hdf5",
                "../hdf5/glove-200-angular.hdf5",
                "../hdf5/fashion-mnist-784-euclidean.hdf5",
                "../hdf5/sift-128-euclidean.hdf5");

        var mGrid = List.of(16, 24, 32, 48);
        var efConstructionGrid = List.of(100, 200, 400);
        var efSearchFactor = List.of(1, 2);
        var diskOptions = List.of(true, false);
```

[bench_ada_hft5.txt](https://github.com/jbellis/jvector/files/12610987/bench_ada_hft5.txt)
![hdf5fashion-mnist-784-euclideanhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/e007b1a6-be72-420b-8599-d5dc41dba268)
![hdf5glove-100-angularhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/99aa27b7-7c0d-4da8-b802-f07043e3ab31)
![hdf5glove-200-angularhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/a9f9dea2-b230-4923-81b3-608ddb5c870c)
![hdf5nytimes-256-angularhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/734da775-f33b-49d0-ab7a-6bba43029ca1)
![hdf5sift-128-euclideanhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/572798c8-3b40-4a07-9782-0ae1008a1cb3)
![ivecpages_ada_002_plot](https://github.com/jbellis/jvector/assets/8622884/bbf2a9f4-83f7-47b2-a4c9-12dc28a64424)

**Comment by jbellis** [comment]
First graph includes PQ=0, is that a bug in the plot?

**Comment by jbellis** [comment]
i think something is broken w/ the last one (possibly w/ the inputs), recall of 0.003 is way too low

**Comment by jbellis** [comment]
I would like to see graphs of the plots constrained to PQ of 1/8 original size (current one-size-fits-all setting), and 1/16; if recall does not drop significantly at overquery=2, then also include 1/32

**Comment by dlg99** [comment]
PQ=0 is filled on the chart when pq is not used (diskOptions == false)

**Comment by dlg99** [comment]
this is ada 100k with dataset downloaded from s3 (previous was from gdrive+slack) and PQ as
```java
        List<Integer> pqDimensions = new ArrayList<>();
        int dims = ds.baseVectors.get(0).length;
        for (int i = 2; i <= 32; i *= 2) {
            if (dims / i > 1) {
                pqDimensions.add(dims / i);
            }
        }
```
[bench_ada_100k.txt](https://github.com/jbellis/jvector/files/12612892/bench_ada_100k.txt)
![ivec2100kpages_ada_002_100k_plot](https://github.com/jbellis/jvector/assets/8622884/1786cfb1-6f0f-4f34-9010-f6643a9abde9)

**Comment by dlg99** [comment]
1M does not work because "MappedRandomAccessReader doesn't support large files"

**Comment by jbellis** [comment]
that's addressed in main branch, but 100k is fine for now

**Comment by dlg99** [comment]
Other datasets with the same selection of PQ:
[bench_others.txt](https://github.com/jbellis/jvector/files/12615214/bench_others.txt)
![hdf5fashion-mnist-784-euclideanhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/d0ee1c19-2522-4c3b-856a-95b3522eca84)
![hdf5glove-100-angularhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/8e53573d-bbd4-4c15-b769-2381c0fe153e)
![hdf5glove-200-angularhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/92841f3d-b76d-484c-a05f-0b06e960fe69)
![hdf5nytimes-256-angularhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/46b8b2c0-3add-477b-abed-18172830df2e)
![hdf5sift-128-euclideanhdf5_plot](https://github.com/jbellis/jvector/assets/8622884/a8f8ff63-da82-4799-8d79-78fd2cc145fd)

**Comment by jbellis** [comment]
Going back to the original goal of evaluating PQ on Ada002 embeddings -- it looks like this is the first dataset we've found where even at 1/8 the size the recall at 16/100/OQ=2 is worse than the recall at 16/100/OQ=1/PQ=Off.  So being even more aggressive with PQ is not warranted.

**Comment by jbellis** [comment]
```
PQ@768 build 63.70s,
PQ encode 4.85s,
Build M=16 ef=100 in 15.08s with 0.40 short edges
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  Query PQ=false top 101/1 recall 0.9434 in 11.77s after 146464790 nodes visited
  Query PQ=true top 101/1 recall 0.9201 in 72.69s after 147004020 nodes visited
  Query PQ=false top 101/2 recall 0.9702 in 22.05s after 250168950 nodes visited
  Query PQ=true top 101/2 recall 0.9703 in 123.74s after 251120730 nodes visited
```

I was looking at the wrong numbers in your graph (seduced by 1536/8=192)

**Comment by jbellis** [comment]
```
PQ@384 build 35.77s,
PQ encode 3.04s,
Build M=16 ef=100 in 15.49s with 0.40 short edges
  Query PQ=false top 101/1 recall 0.9463 in 2.60s after 29129956 nodes visited
  Query PQ=true top 101/1 recall 0.8293 in 7.76s after 29300004 nodes visited
  Query PQ=false top 101/2 recall 0.9719 in 4.34s after 49809210 nodes visited
  Query PQ=true top 101/2 recall 0.9629 in 12.88s after 50224696 nodes visited
```
```
PQ@192 build 22.40s,
PQ encode 1.45s,
Build M=16 ef=100 in 15.10s with 0.40 short edges
  Query PQ=false top 101/1 recall 0.9427 in 2.68s after 30315300 nodes visited
  Query PQ=true top 101/1 recall 0.6806 in 4.19s after 31296206 nodes visited
  Query PQ=false top 101/2 recall 0.9691 in 4.69s after 51024144 nodes visited
  Query PQ=true top 101/2 recall 0.8682 in 6.49s after 51692598 nodes visited
```  

from this very small sample it looks like it's okay to reduce to 384 if you're doing OQ=2, but not 192

**Comment by jbellis** [comment]
[I switched from numruns=10 to numruns = 2 is why all the query times got much smaller]
