### ISSUE TITLE
Add Java21 support

### ISSUE THREAD

**Issue by tjake** [jbellis/jvector#81]

**Comment by jbellis** [comment]
it looks like it's a one-line change in VectorizationProvider to support 19 as well (Panama API is unchanged 19/20)  but maven might be more work

**Comment by jbellis** [comment]
if it's not much work we might as well support 19 too (but 21 is way more important)

**Comment by JeremiahDJordan** [comment]
Not sure the point of supporting 19 at this point?  Will anyone actually use the 19 short term releases?

**Comment by jbellis** [comment]
If it's just tweaking a minversion somewhere, why not?

**Comment by tjake** [comment]
Looks like nothing todo here.  If we want java 19 make a new issue?
