### ISSUE TITLE
Rename CachingGraphIndex.BFS_DISTANCE?

### ISSUE THREAD

**Issue by ShaunakDas88** [jbellis/jvector#96]
This is a cosmetic thing, but always good to avoid confusion.

[CachingGraphIndex.BFS_DISTANCE](https://github.com/jbellis/jvector/blob/main/jvector-base/src/main/java/io/github/jbellis/jvector/disk/CachingGraphIndex.java#L28) is a parameter used to populate `GraphCache`. Currently, we are actually performing DFS with a stack (the [recursive call stack](https://github.com/jbellis/jvector/blob/main/jvector-base/src/main/java/io/github/jbellis/jvector/disk/GraphCache.java#L69-L94)), rather than BFS with a queue.

Immediate possible "fixes":
- Simplest thing is rename `BFS_DISTANCE` to `DFS_DISTANCE` (or more generically just `DISTANCE`) , and keep the current DFS implementation
- Slightly more work is to keep the naming and re-implement our graph traversal using BFS. Our queue would hold `(remaining_steps, node)` pairs

Also, one other minor thing. The set of nodes that are distance = 0 from the entry node should correspond to precisely the entry node; [this check](https://github.com/jbellis/jvector/blob/main/jvector-base/src/main/java/io/github/jbellis/jvector/disk/GraphCache.java#L43) should probably be a strict `< 0` check.

**Comment by jbellis** [comment]
Thanks!
